### ISSUE TITLE
EACCESS error for junit.xml

### ISSUE THREAD

**Issue by Pushplaybang** [ziishaned/jest-reporter-action#2]
I get an EACCESS error for the junit.xml file, in my action.

my config:

```yaml
name: Jest Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2
    - name: Report Coverage
      uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "yarn jest --coverage"


```
