### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by patoncrispy** [ziishaned/jest-reporter-action#3]
Just tried to run this action and got the error: Cannot read property 'number' of undefined. Providing github token and using default `test-command`.

**Comment by DeadIine** [comment]
+1 same error here

**Comment by jperasmus** [comment]
Looks like the error is coming from here: https://github.com/ziishaned/jest-reporter-action/blob/872c1051350ecaf625ba2490d68e7cb63854b44c/index.js#L19

**Comment by romeovs** [comment]
Looks like this might be the issue: https://github.com/actions/checkout/issues/58#issuecomment-589447479

**Comment by ziishaned** [comment]
@patoncrispy Thanks for opening the issue. Sorry for the late response. I will look into it this weekend :)

**Comment by romeovs** [comment]
@ziishaned I'm testing out some code changes that will fix this. Should be able to create a PR soon!

**Comment by ziishaned** [comment]
> @ziishaned I'm testing out some code changes that will fix this. Should be able to create a PR soon!

@romeovs Thanks for the help 👍

**Comment by gndelia** [comment]
+1 I just checked it and I got the same error

**Comment by tlow92** [comment]
I'm using this fork, which fixed the issue. 
https://github.com/ChristiaanScheermeijer/jest-reporter-action

works fine for me, maybe you can merge the changes? @ziishaned

**Comment by daniel-vc** [comment]
Am having the same issue. When can this be  fixed / merged @ziishaned?

**Comment by bartlomiejzuber** [comment]
Same here. Do you need any help with fixing it ?

**Comment by ziishaned** [comment]
@bartlomiejzuber I tested this action on my private repo and the action ended successfully. Can you please enlist all the steps to reproduce this issue

**Comment by bartlomiejzuber** [comment]
@ziishaned Hmm quite odd but I've just switched from https://github.com/ChristiaanScheermeijer/jest-reporter-action fork to your action(to see what might be the issue here) and it worked just fine. 😃 I will let you know if problem show up again.

**Comment by mohanraj-r** [comment]
Faced the same issue with yarn v1.22.4 and jest v25.2.3. 
Have only `coverageThreshold` override in `jest.config.js`. 
Switched to `romeovs/lcov-reporter-action@v0.2.16` and now have it working.

**Comment by femioladeji** [comment]
I experienced this same issue also and I think it's because `await githubClient.repos.listPullRequestsAssociatedWithCommit` returned an empty `data` array.
I think the `prNumber` can be retrieved from the context object `context.payload.number` thereby removing the need to make this request `githubClient.repos.listPullRequestsAssociatedWithCommit`

**Comment by RALMAZ** [comment]
+1

**Comment by danawoodman** [comment]
I'm having this issue with Yarn `v1.22.4`, node `v14.0.0`

```yml
      - name: Jest Code Coverage Report
        uses: ziishaned/jest-reporter-action@0.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: yarn coverage
```

**Comment by xylesoft** [comment]
I'm also encountering this bug with the following error:
```

1s
    test-command: yarn test
Run ziishaned/jest-reporter-action@0.1.1
  with:
    github-token: ***
    test-command: yarn test
##[error]Cannot read property 'number' of undefined
```

Running with `Jest 26.0.1`, `yarn v1.22.4` and Node 10 & 12 with the following configuration: 
```
jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --dev
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: yarn test  
```
