### ISSUE TITLE
Empty coverage report

### ISSUE THREAD

**Issue by washingtonsoares** [ziishaned/jest-reporter-action#4]
The coverage output  it's being always empty.

![image](https://user-images.githubusercontent.com/5726140/74234144-f6622580-4caa-11ea-8b21-1157a9919b80.png)

My config:

```yml
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run eslint

    - uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "npm run test:coverage"
```
