### ISSUE TITLE
I have a failed: npx coverage-percentage

### ISSUE THREAD

**Issue by bratorimatori** [ziishaned/jest-reporter-action#6]
Not sure what seams to be the problem here. 
I added the CI job as instructed but it fails.

This is my job:

```
name: JestCodeCoverage
on: push

jobs:
  codecoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run install
        run: npm install
      - name: Jest Code Coverage Action
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: npm run test:coverage
```

What I get is very strange error that I can make since off. File get generated when I run my commande locally so I am not really sure why can't it find it.

```
Command failed: npx coverage-percentage ./coverage/lcov.info --lcov
npx: installed 2 in 1.485s
ENOENT: no such file or directory, open './coverage/lcov.info'
```
